name: model_retrain_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - scikit-learn=1.0.2
  - pandas=1.4.2
  - numpy=1.22.3
  - mlflow=1.25.1
  - pip:
    # Add any pip-specific dependencies here
    # - your-custom-library==1.0